### PR TITLE
Create phraseActions.yml & add self assignment on comment

### PR DESCRIPTION
**Pull request by droxtal**
/assignme or /assign me - assigns the issue to commentor

### CODE REVIEW

**Comment by kry0sc0pic** [comment]
is there anyway to make the phrase trigger case-insensitive?

**Comment by droxtal** [comment]
I think yes

**Comment by droxtal** [comment]
> GitHub ignores case when comparing strings.

Source: https://docs.github.com/en/actions/learn-github-actions/expressions#operators

**Comment by kry0sc0pic** [comment]
random edge case i though of.

If someone types '... test/assignment ...'. This would get the issue assigned to that person who didn't actually want to be assigned.

**Comment by kry0sc0pic** [comment]
might as well add a '/unassignme' and '/unassign me'. That way we don't have to worry about unintentional assigns lol.

**Comment by droxtal** [comment]
You can unassign yourself from UI

**Comment by kry0sc0pic** [comment]
mb, I didn't know.

LGTM

**Comment by droxtal** [comment]
> If someone types '... test/assignment ...'. This would get the issue assigned to that person who didn't actually want to be assigned.

tried fixing it.

Any more edge cases?

**Comment by droxtal** [comment]
I actually don't like this approach.
At this point I think the logic should be handled inside bash.

**Comment by droxtal** [comment]
> I actually don't like this approach.
> At this point I think the logic should be handled inside bash.

I am saying this because I want to make it able to handle things like assigning tags, stale issues, running tests, running scans, etc.

**Comment by IndraReddy5** [comment]
Yeah, even I don't like the way, we are trying to fix the edge cases...
It's looking like more hard-coded cases just to handle user inputs.
Is it possible to use a regex match there and why do we even need to handle all these cases, I think /assignme or /assign me is straightforward to any new users.

**Comment by droxtal** [comment]
> Is it possible to use a regex match

Yes, but the workflow will every time have to spin up ubuntu & do regex in bash. Right now bash only sends the POST request.

**Comment by droxtal** [comment]
Or maybe we can go ahead & make the bot interact on GitHub too or make another bot for this.

**Comment by droxtal** [comment]
I have a hunch that all this might be possible without a full fledged bot.

**Comment by kry0sc0pic** [comment]
GPT-4 suggested this. can you test this?

Prompt:
```
I want to build a github action that will assign an issue to a specific user on which they comment `/assignme` or `/assign me`. But it should only work when nothing else is in the message
```

Code:
```yaml
name: 'Assign Issue'
on:
  issue_comment:
    types: [created]

jobs:
  assign_to_user:
    runs-on: ubuntu-latest
    steps:
    - name: Assign issue to user
      uses: actions/github-script@v3
      with:
        script: |
          const commentBody = context.payload.comment.body;
          const issue = context.payload.issue;
          if (commentBody.trim() === "/assignme" || commentBody.trim() === "/assign me") {
            const assignee = context.payload.comment.user.login;
            github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              assignees: [assignee]
            })
          }
```

**Comment by droxtal** [comment]
This did create an Ubuntu instance. It is more inefficient as it spins up Ubuntu on every comment. The workflow got triggered on `test/assignment`.

https://github.com/actions/github-script needs Ubuntu to run

**Comment by droxtal** [comment]
A simpler way is to just ask the command users to add a leading & trailing space for it to work.

**Comment by sinsniwal** [comment]
I think starting with `\assign me` will work, we dont need extra ifs

**Comment by sinsniwal** [comment]
@droxtal  Thanks 👍 , looks good to me; maybe in the future, we can add more functionality
Welcome aboard ⛵

**Review by sinsniwal — APPROVED** [review]

**Review by sinsniwal — APPROVED** [review]

**Pull request merged**
