### PR TITLE
Bot Rewrite & Restructure 

### PR DESCRIPTION
**Pull request by sloth-ontabasco**
# Breaking Changes
## Changes to bot directory structure
```
.
├── bot.py
├── config.py
├── main.py
├── cogs
│   ├── dev.py
│   ├── interaction.py
│   ├── reaction.py
│   ├── slash.py
│   └── verification.py
└── utils
    ├── email_template.txt
    └── helper.py
```
- Renamed cogs/message.py -> cogs/verification.py
- Renamed tools.py -> utils/helper.py
- Renamed email_template.txt -> utils/email_template.txt
- Removed config.ini infavor of config.py and .env
- Removed embeds.py (merged into utils/helper.py)
- Added bot.py
- Added cogs/dev.py

### bot.py
Contains the following classes
- `IITMBot` inherited from `commands.AutoSharedBot`
  - supporting class method `_use_default` creates and returns a default customized instance of `IITMBot`
  - method `load_extension` borrowed from old main.py
  - method `close` gracefully exits async event loop closing all services
- `BotTree` inherited from `app_commands.CommandTree`
  - contains methods defined to log Interaction errors to `#developer-logs` in the server
Apart from these classes, a context manager `log_setup` has also been defined to handle logging 

### main.py
File reads environment variables to start the bot by importing `IITMBot` from bot.py and sets the bot up along with the context manager for logging

### config.py
All *Non-Sensitive* global config variables are set here for the bot.
Sensitive variables are to be placed in a user generated `.env` file as follows
```
DISCORD_BOT_TOKEN="PASTE BOT TOKEN HERE"
SIB_API_KEY="PASTE API KEY HERE"
SIB_SENDER_EMAIL="PLACE EMAIL HERE"
FERNET="PLACE FERNET KEY HERE"
```

### cogs/dev.py
The following bot commands have been added for development, all these commands require the `is_owner` decorater limiting their use to just the bot owner
**!eval**
Useful to run code on the fly to test stuff. (Dangerous when abused)
image

**!kill**
Kill the bot through discord

**!sync_apps**
Synchronize slash commands to the bot

**!clear_apps**
Remove all slash commands from the bot

### verification.py
Contains all the previous functionality of message.py PLUS...
- added create command that sends the verification message with buttons in the invoked channel instead of relying on `on_message`
- added send command to get sent the verification confirmation embed
Both these commands are protected by the admin_only decorator which can be modified in utils/helper.py

# P.S README.md has not been updated to reflect these changes! Need a proper write-up for it which can be attached to this PR

### CODE REVIEW

**Comment by sinsniwal** [comment]
In cogs/dev.py, can we make all admin commands hidden and restricted? Apart from that, everything seems fine

**Comment by sloth-ontabasco** [comment]
> In cogs/dev.py, can we make all admin commands hidden and restricted? Apart from that, everything seems fine

The commands under cogs/dev.py are protected by discord.py's inbuilt security decorator `commands.is_owner()` restricting its use only to bot owners. You can set the owner id in config.py to the admin ID and the two protectors will act the same!

**Comment by sinsniwal** [comment]
pr326
here kill command is not protected by is_owner, and I think it will be better if we hide all of these commands, including kill, sync_apps, clear_apps, and eval, so that writing the help slash command will become easier.

**Comment by sloth-ontabasco** [comment]
commit d79fbcc address the issues

**Review by sinsniwal — APPROVED** [review]
All issues resolved, suitable for merging

**Pull request merged**
